config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :host_users, controllers: {
    sessions:      'host_users/sessions',
    passwords:     'host_users/passwords',
    registrations: 'host_users/registrations'
  }                 
  root "users#index"
  
  resources :users, only: [:index,  :show, :new, :create, :edit, :update] 

  resources :host_users, only: [:index, :show, :new, :create, :edit, :update] do 
    collection do
      get :search
    end 
  end

  resources :books, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:index, :create]
  end
  

  

          
end

app/models/host_user.rb
class HostUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books

         
  mount_uploader :image, ImageUploader

  def self.search(search)
    HostUser.where('name LIKE(?)', "%#{search}%")
  end

end

app/controllers/host_users/confirmations_controller.rb
# frozen_string_literal: true

class HostUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/host_users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class HostUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/host_users/passwords_controller.rb
# frozen_string_literal: true

class HostUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/host_users/registrations_controller.rb
# frozen_string_literal: true

class HostUsers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  
  # GET /resource/edit
  
  # PUT /resource
  
  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/host_users/sessions_controller.rb
# frozen_string_literal: true

class HostUsers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/host_users/unlocks_controller.rb
# frozen_string_literal: true

class HostUsers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/host_users_controller.rb
class HostUsersController < ApplicationController
    before_action :set_host_user, except: [:index, :show, :search]

    def index
        @host_users = HostUser.all
        @host_user = HostUser.find(params[:id])
    end

    def show
        @host_user = HostUser.find(params[:id])
        @books = @host_user.books.order("created_at DESC")
        @book = Book.find(params[:id])
    end

    def new
        @host_user = HostUser.new
    end

    def create
        @host_user = HostUser.new
        redirect_to host_user_path(@host_user)
    end

    def edit
        @host_user = HostUser.find(params[:id])
    end

    def update
        @host_user = HostUser.find(params[:id])
        if @host_user.update(host_user_params)
            @host_user.image="#{@host_user.id}.jpg"
            image=params[:image]
        end
        redirect_to host_user_path(@host_user)
    end

    def search
        @host_users = HostUser.search(params[:keyword])
        respond_to do |format|
            format.html
            format.json
        end
    end    

    private
    def host_user_params
        params.permit(:name, :email, :image, :text)
    end

    def set_host_user
        @host_user = HostUser.find(params[:id])
    end

    def ensure_correct_user
        if @current_host_user.id != params[:id].to_i
        flash[:notice] = "権限がありません"
        redirect_to("/posts/index")
       end
    end

    
end

app/views/host_users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 編集(ホストユーザー)
      %h5 プロフィール画面を編集する
    .account-page__inner--right.user-form
      = form_for @host_user, :multipart => true do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email, autofocus: true
        .field
          .field-label
            = f.label :image do
              = f.file_field :image
        .field
          .field-label
            = f.label :text 
          .field-input
            = f.text_area :text
        .actions
          %input{type: "submit", class:"submit-btn"}

app/views/host_users/search.html.haml
= form_with(url: search_host_users_path, local: true, method: :get, class: "search-form") do |form| 
    = form.text_field :keyword, placeholder: "ユーザーを検索する", class: "search-input"
    = form.submit "検索", class: "search-btn"

.contents_row                         
    - @host_users.each do |host_user|                            
        = link_to "#{host_user.name}", "#{host_user.id}"

app/views/host_users/show.html.haml
.host-show-header
    .host-show-header-logo
        = @host_user.name 
    .host-show-header-menu
        = link_to "ログアウト", destroy_host_user_session_path, method: :delete, class: 'btn'
        = link_to "編集する", edit_host_user_path, class: "btn"


    
.host-show-main 
    .host-show-main-container
        = image_tag "#{@host_user.image}", alt: "「編集する」からプロフィール画面,自己紹介文を設定することができます"
    .host-profile
        = "#{@host_user.text}" 

    .host-show-posts-container 
        .host-show-posts-container1
            =link_to "イベント投稿する", new_book_path(book_id: @book) ,class: "btn"
        
        
        .host-show-posts-main
            = render @books