config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :host_users, controllers: {
    sessions:      'host_users/sessions',
    passwords:     'host_users/passwords',
    registrations: 'host_users/registrations'
  }                 
  root "users#index"
  
  resources :users, only: [:index,  :show, :new, :create, :edit, :update] 

  resources :host_users, only: [:index, :show, :new, :create, :edit, :update] do 
    collection do
      get :search
    end 
  end

  resources :books, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:index, :create]
  end
  

  

          
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reservations, dependent: :destroy
  has_many :books, through: :reservations
  has_many :host_users
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
    end

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id]) 
        @host_users = HostUser.all                                                           
    end

    def create
        redirect_to user_path(@user)
    end

    def search
        @host_users = HostUser.search(params[:keyword])
        @host_user = HostUser.find(params[:id])
        respond_to do |format|
            format.html
            format.json
        end

        redirect_to users_path(@user)
    end

    private
    def user_params
      params.require(:user).permit(:name, :email, :host_user_id)
    end

    def ensure_correct_user
        if @current_user.id != params[:id].to_i
        flash[:notice] = "権限がありません"
        redirect_to("/posts/index")
       end
    end

    
end

app/views/users/index.html.haml
.header
    .header-logo
        %h1 booking-appへようこそ
        %p 〜さあ、始めよう
        .header-menu
            = link_to '予約用ユーザーとしてログイン', new_user_session_path(@user) ,class: 'btn'
            = link_to '告知用ユーザーとしてログイン', new_host_user_session_path(@host_user) ,class: 'btn'

        .nav
            %ul
                %li<
    
.main
    .main-container
        .main-image
            
        .posts-container
            .post-container2 
                = link_to '予約用ユーザーとしてログイン', new_user_session_path(@user) 
                = link_to '告知用ユーザーとしてログイン', new_host_user_session_path(@host_user) 

app/views/users/search.html.haml
= form_with(url: search_host_users_path, local: true, method: :get, class: "search-form") do |form| 
    = form.text_field :keyword, placeholder: "ユーザーを検索する", class: "search-input"
    = form.submit "検索", class: "search-btn"

.contents_row                         
    - @host_users.each do |host_user|                            
        = render partial: "form" ,locals: { user: user }                   

app/views/users/show.html.haml
.show-header
    .show-header-logo
        =current_user.name + "様のページ"
    .show-header-menu
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
.show-main
    .show-main-container
        = image_tag "green.jpg", alt: "写真"   
        %p 一覧
                 
    .show-posts-container
        = form_with(url: search_host_users_path, local: true, method: :get, class: "search-form") do |form| 
            = form.text_field :keyword, placeholder: "ユーザーを検索する", class: "search-input"

        .contents_row
            - @host_users.each do |host_user| 
                = render partial: "form" ,locals: { host_user: host_user }                        
       