config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  devise_for :host_users, controllers: {
    sessions:      'host_users/sessions',
    passwords:     'host_users/passwords',
    registrations: 'host_users/registrations'
  }                 
  root "users#index"
  
  resources :users, only: [:index,  :show, :new, :create, :edit, :update] 

  resources :host_users, only: [:index, :show, :new, :create, :edit, :update] do 
    collection do
      get :search
    end 
  end

  resources :books, only: [:index, :new, :create, :show] do
    resources :reservations, only: [:index, :create]
  end
  

  

          
end

app/models/book.rb
class Book < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :host_user
    has_many :reservations
    has_many :user, through: :users
    validates :title, presence: true, unless: :image?
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_host_user, except: [:show, :create,:new]
    before_action :move_to_index, except: [:index, :new, :create, :show]


    def index    
        @books = @host_user.books.includes(:host_user)
    end

    def show
        @book = Book.find(params[:id])
        @host_user = @book.host_user
    end

    def new       
        @book = Book.new
    end

    def create 
        @book = Book.new(book_params)
        if @book = Book.create(book_params)
            @book.image = "#{@book.id}.jpg"  
            image=params[:image] 
        end
        redirect_to host_user_path(current_host_user)
    end



    private


    def book_params
        params.permit(:title, :text, :image, :start_dt, :end_dt, :id).merge(host_user_id: current_host_user.id )
    end

    def reservation_params
        params.permit(:id).merge(user_id: current_user.id)
    end

    def move_to_index
        redirect_to action: :index unless host_user_signed_in?
    end

    def set_host_user
        @host_user = HostUser.find(params[:host_user_id])
    end


end

app/views/books/_book.html.haml
.book-info
    = link_to book_path(book.id) do
        .book-data1
            イベント名:
            = book.title
        .book-info2
            .book-data2
                = image_tag "#{book.image}"
            .book-data3
                = book.text
        .book-data4
            イベント開催日時:  
            = book.start_dt.strftime("%Y年%m月%d日")
        .book-data5
            予約締め切り:
            = book.end_dt.strftime("%Y年%m月%d日")

app/views/books/index.html.haml
.wrapper
  = render 'book'

app/views/books/new.html.haml
= form_with(url: books_path, local: true, method: :post) do |f|

    = f.hidden_field :book_id, value: @book.id 
    .book-first
    = f.label :start_dt do
        開催日 
    = f.text_field :start_dt, class: "form-control datetimepicker-input", id: "start_dt", data: {toggle: "datetimepicker", target: "#start_dt"}
    .book-second
    = f.label :end_dt do
        締め切り
    = f.text_field :end_dt, class: "form-control datetimepicker-input", id: "end_dt", data: {toggle: "datetimepicker", target: "#end_dt"}
    .book-third
    = f.label :イベント名
    = f.text_field :title 
    .book-fourth
    = f.label :イベント詳細
    = f.text_area :text
    .book-fifth
    = f.label :イメージ写真 do
        = f.file_field :image
                                    
    = f.submit "送信する", class: "btn btn-danger btn-wide"  

app/views/books/show.html.haml
= form_for [@book, @book.reservations.new] do |f|
    = f.hidden_field :book_id, value: @book.id 

    = f.submit "予約する", class: "btn btn-danger btn-wide"